q_states:
  q_list:
    - 'q0'    
    - 'q1'    
    - 'q2'    
    - 'q3'   
    - 'qaccept'
    - 'qreject'
  initial: 'q0'
  final: 
    - 'qaccept'
    - 'qreject'
alphabet:
  - 'a'
  - 'b'
tape_alphabet:
  - 'a'
  - 'b'
  - '_'
  - 'X'
  - 'Y'
delta:
  # Estado q0: Inicio y marcado del primer carácter
  - params:
      initial_state: 'q0'
      mem_cache_value: null
      tape_input: 'a'
    output:
      final_state: 'q1'
      mem_cache_value: 'a'
      tape_output: 'X'
      tape_displacement: 'R'
  - params:
      initial_state: 'q0'
      mem_cache_value: null
      tape_input: 'b'
    output:
      final_state: 'q1'
      mem_cache_value: 'b'
      tape_output: 'Y'
      tape_displacement: 'R'
  
  # Estado q1: Moviéndose hacia la derecha
  - params:
      initial_state: 'q1'
      mem_cache_value: null
      tape_input: 'a'
    output:
      final_state: 'q1'
      mem_cache_value: null
      tape_output: 'a'
      tape_displacement: 'R'
  - params:
      initial_state: 'q1'
      mem_cache_value: null
      tape_input: 'b'
    output:
      final_state: 'q1'
      mem_cache_value: null
      tape_output: 'b'
      tape_displacement: 'R'
  - params:
      initial_state: 'q1'
      mem_cache_value: null
      tape_input: '_'
    output:
      final_state: 'q2'
      mem_cache_value: null
      tape_output: '_'
      tape_displacement: 'L'
  
  # Estado q2: Verificando último carácter y moviéndose hacia la izquierda
  - params:
      initial_state: 'q2'
      mem_cache_value: 'a'
      tape_input: 'a'
    output:
      final_state: 'q3'
      mem_cache_value: null
      tape_output: 'X'
      tape_displacement: 'L'
  - params:
      initial_state: 'q2'
      mem_cache_value: 'b'
      tape_input: 'b'
    output:
      final_state: 'q3'
      mem_cache_value: null
      tape_output: 'Y'
      tape_displacement: 'L'
  - params:
      initial_state: 'q2'
      mem_cache_value: 'a'
      tape_input: 'b'
    output:
      final_state: 'qreject'
      mem_cache_value: null
      tape_output: 'b'
      tape_displacement: 'N'
  - params:
      initial_state: 'q2'
      mem_cache_value: 'b'
      tape_input: 'a'
    output:
      final_state: 'qreject'
      mem_cache_value: null
      tape_output: 'a'
      tape_displacement: 'N'
  
  # Estado q3: Regresando al inicio
  - params:
      initial_state: 'q3'
      mem_cache_value: null
      tape_input: 'a'
    output:
      final_state: 'q3'
      mem_cache_value: null
      tape_output: 'a'
      tape_displacement: 'L'
  - params:
      initial_state: 'q3'
      mem_cache_value: null
      tape_input: 'b'
    output:
      final_state: 'q3'
      mem_cache_value: null
      tape_output: 'b'
      tape_displacement: 'L'
  - params:
      initial_state: 'q3'
      mem_cache_value: null
      tape_input: 'X'
    output:
      final_state: 'q0'
      mem_cache_value: null
      tape_output: 'X'
      tape_displacement: 'R'
  - params:
      initial_state: 'q3'
      mem_cache_value: null
      tape_input: 'Y'
    output:
      final_state: 'q0'
      mem_cache_value: null
      tape_output: 'Y'
      tape_displacement: 'R'
  
  # Transiciones 
  - params:
      initial_state: 'q1'
      mem_cache_value: null
      tape_input: 'X'
    output:
      final_state: 'qaccept'
      mem_cache_value: null
      tape_output: 'X'
      tape_displacement: 'N'
  - params:
      initial_state: 'q1'
      mem_cache_value: null
      tape_input: 'Y'
    output:
      final_state: 'qaccept'
      mem_cache_value: null
      tape_output: 'Y'
      tape_displacement: 'N'

simulation_strings:
  - 'abba'
  - 'aabb'
  - 'aba'
  - 'abbaabba'